version: '3'

services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: strapidb
    ports:
      - "5432:5432"
    networks:
      - dependencies-network

networks:
  dependencies-network:
    driver: bridge
