# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql-docker-local
#     # restart: always
#     environment:
#       - MYSQL_DATABASE=strapidb
#       - MYSQL_USER=admin
#       - MYSQL_PASSWORD=admin
#       - MYSQL_ROOT_PASSWORD=12345
#     ports:
#       - '3306:3306'
version: '3'

services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: strapidb
    ports:
      - "5432:5432"
    networks:
      - dependencies-network

networks:
  dependencies-network:
    driver: bridge
