import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import SectionDestaque from "@/components/SectionDestaque/SectionDestaque";
import SectionPersona from "@/components/SectionPersona/SectionPersona";

const inter = Inter({ subsets: ['latin'] })
const HOST = 'http://localhost:1337';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SectionDestaque/>
        <SectionPersona/>
      </main>
    </>
  )
}
